### ISSUE TITLE
CSS Variables in SPFx projects

### ISSUE THREAD

**Issue by fcatinot** [StfBauer/spfx-uifabric-themes#7]
Hello,
I want use CSS Variables in SPFx projects, but when i realise gulp bundle --ship. I have this error

![capture](https://user-images.githubusercontent.com/27960780/47719962-0b997900-dc4d-11e8-9e47-93304edd6aa6.PNG)

I can't uglify es6.
If i transform node-module/spfx-uifabric-themes/index.js to es5 format. It works.
Do you have another solution?

**Comment by StfBauer** [comment]
Thank you for bringing this to my attention @fcatinot

Can you share a basic sample how you use it? Would be interesting how you set the things up and gives me a better chance to reproduce it.

In fact, it is just plain JavaScript old and not ES6 or ES5.

**Comment by fcatinot** [comment]
I copied your example (https://github.com/StfBauer/spfx-uifabric-themes/blob/master/docs/css-variables.md).
node v8.12.0
SharePoint Framework 1.6

**Comment by StfBauer** [comment]
Thank you @fcatinot - Published a new version. Can you check it. Thank you.

**Comment by fcatinot** [comment]
Thank you, it works fine :)

**Comment by StfBauer** [comment]
Great and thanks again for letting me know about the issue.
